### ISSUE TITLE
Help with radio live streaming

### ISSUE THREAD

**Issue by neowinston** [star2dev/Video.js-HLS-Player-for-WordPress#1]
I'd like to hide the video screen, just to play the HLS live stream for a radio station and showing the play/pause controls. Is that possible via .css? Should I look into the .php file?

Your help will be much appreciated. Thank you!

**Comment by star2dev** [comment]
Hi, 

You'd need to change the HTML element from `video` to `audio` in videojs-hls-player.php (Line: 267 + 270)

Use `poster="http://example.com/wp-content/uploads/my-radio-station-artwork.jpg"` in the shortcode to set a static image to display during audio playback - This could be album art or radio station artwork

Alternatively, JWPlayer offers audio only HLS support

Cheers
