### ISSUE TITLE
High Sierra public beta and Firefox can't play m3u8

### ISSUE THREAD

**Issue by lvnilesh** [star2dev/Video.js-HLS-Player-for-WordPress#2]
Thanks for creating this plugin for Wordpress.

Using High Sierra public beta and Firefox. Playing an m3u8 source, I notice this error. 

```
specified “type” attribute of “application/x-mpegURL” is not supported. Load of media resource failed.
```

**Comment by star2dev** [comment]
Maybe this thread will help: https://github.com/videojs/videojs-contrib-hls/issues/653 

Alternatively, check for Cross Origin "CORS" issues too, as browsers that don't natively support HLS fallback to the flash player which needs permissions to handle data across domains.

**Comment by lvnilesh** [comment]
Same seteup works OK on latest Sierra not just on high sierra public beta so ruling out CORS issue.
